# Git hooks config
post_commit_tests: true
pre_push_tests: true

# Your actual test commands
#
# Example:
#
# ```
# commands:
# - bundle exec rubocop
# - bundle exec rspec
# ```
commands:
 - bundle exec rubocop -A
 - bundle exec rspec --format progress

